# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('id_arduino', models.IntegerField()),
                ('value', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='arduino',
            name='crypto_key',
        ),
    ]
