# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 17:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('smarthouse', '0002_auto_20160715_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_arduino', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='arduino',
            name='crypto_key',
            field=models.CharField(default=datetime.datetime(2016, 7, 15, 17, 36, 57, 669859, tzinfo=utc), max_length=40),
            preserve_default=False,
        ),
    ]
